import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Home from "./home";
import Login from "./login";
import Register from "./register";

export default function index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Register></Register>
    </div>
  );
}
